import Head from 'next/head'
import NavBar from "../components/Navigation/Nav";
import Header from "../components/Header/Header";
import Sponsor from '../components/Sponsor/Sponsor';
import Status from '../components/Status/Status';
import Services from '../components/Services/Services';
import Cost from '../components/Cost/Cost';
import Trial from '../components/Trial/Trial';
import HeroCard from '../components/HeroCard/HeroCard';
import Medel from '../components/Medel/Medel';
import Footer from '../components/Footer/Footer';

import styles from '../styles/Home.module.css'


export default function Home() {


  return (
    <div className={styles.container}>
      <Head>
        <title>Bright Local Web App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <>
        <NavBar />
        <Header />
        <Sponsor />
        <Status />
        <Services />
        <Cost />
        <Trial />
        <HeroCard />
        <Medel />
        <Footer />

      </>


    </div>
  )
}
